# Need GNUMake
# Created and maintanced by wuya
# v 1.0

# need edit

# PROJECTTYPE  EXE:executable, LIB:static lib, DLL:shared lib
PROJECTTYPE=DLL
ARGS=
INCDIR=.
LIBSDIR=.
LIBS=
EXCLUDE=main3.cpp main4.cpp

include ../common.mak

