# Need GNUMake
# Created and maintanced by wuya
# v 1.0

# need edit

# PROJECTTYPE  EXE:executable, LIB:static lib, DLL:shared lib
PROJECTTYPE=LIB
ARGS=
INCDIR=.
LIBSDIR=.
LIBS=
EXCLUDE=

include ../common.mak

