# Need GNUMake
# Created and maintanced by wuya
# v 1.0

# need edit

# PROJECTTYPE  EXE:executable, LIB:static lib, DLL:shared lib
PROJECTTYPE=EXE
ARGS=
INCDIR=../mod1 ../mod1_static
LIBSDIR=../../lib
LIBS=mod1 mod1_static
EXCLUDE=main3.cpp main4.cpp

include ../common.mak

