LIBPREFIX=lib
LIBPOSTFIX=.a
DLLPREFIX=lib
DLLPOSTFIX=.sl

DLL_COMPILER_FLAG=+z
DLL_LINKER_FLAG=-b +DA2.0w
ARFLAGS=-rs
CXXFLAGS=-AA -g +DA2.0w
release: CXXFLAGS=-AA -O +DA2.0w
LDFLAGS=-AA -Wl,+s +DA2.0w
DEPENDENCYFLAG=1
DFLAGS=-AA +make -E

